name: meet-mate-backend

services:
  postgres:
    image: postgres:16.3-alpine3.20
    volumes:
      - "${POSTGRES_DATA_DIR}/data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "${POSTGRES_PORT}:5432"